package mapreduce

import (
	"encoding/json"
	"fmt"
	"hash/fnv"
	"io/ioutil"
	"os"
	"log"
)

func doMap(
	jobName string, // the name of the MapReduce job
	mapTask int, // which map task this is
	inFile string,
	nReduce int, // the number of reduce task that will be run ("R" in the paper)
	mapF func(filename string, contents string) []KeyValue,
) {
	//
	// doMap manages one map task: it should read one of the input files
	// (inFile), call the user-defined map function (mapF) for that file's
	// contents, and partition mapF's output into nReduce intermediate files.
	//
	// There is one intermediate file per reduce task. The file name
	// includes both the map task number and the reduce task number. Use
	// the filename generated by reduceName(jobName, mapTask, r)
	// as the intermediate file for reduce task r. Call ihash() (see
	// below) on each key, mod nReduce, to pick r for a key/value pair.
	//
	// mapF() is the map function provided by the application. The first
	// argument should be the input file name, though the map function
	// typically ignores it. The second argument should be the entire
	// input file contents. mapF() returns a slice containing the
	// key/value pairs for reduce; see common.go for the definition of
	// KeyValue.
	//
	// Look at Go's ioutil and os packages for functions to read
	// and write files.
	//
	// Coming up with a scheme for how to format the key/value pairs on
	// disk can be tricky, especially when taking into account that both
	// keys and values could contain newlines, quotes, and any other
	// character you can think of.
	//
	// One format often used for serializing data to a byte stream that the
	// other end can correctly reconstruct is JSON. You are not required to
	// use JSON, but as the output of the reduce tasks *must* be JSON,
	// familiarizing yourself with it here may prove useful. You can write
	// out a data structure as a JSON string to a file using the commented
	// code below. The corresponding decoding functions can be found in
	// common_reduce.go.
	//
	//   enc := json.NewEncoder(file)
	//   for _, kv := ... {
	//     err := enc.Encode(&kv)
	//
	// Remember to close the file after you have written all the values!
	//
	// Your code here (Part I).
	//

	///**
	//os.Exit(2)
	// 1. 读取文件
	data, err := ioutil.ReadFile(inFile)
	CkErr(err, "读取文件错误")
	if err != nil {
		return
	}
	//os.Exit(1)

	kvResult := mapF(inFile, string(data))
	//os.Exit(3)
	fmt.Println("kvRsult长度---------", len(kvResult))
	//os.Exit(1)

	// 3. 生成临时文件
	intermediateFiles := make([]*os.File, nReduce)
	for i := 0; i < nReduce; i++ {
		intermediateFiles[i], err = os.Create(reduceName(jobName, mapTask, i))
		if err != nil {
			log.Fatal("创建临时文件失败...", reduceName(jobName, mapTask, i))
		}
	}

	// 4. 循环 keyValue, 归并key到相应的reduce, 使用 json.NewEncoder写入正确的文件
	for _, kv := range kvResult {
		enc := json.NewEncoder(intermediateFiles[ihash(kv.Key) % nReduce])
		err := enc.Encode(&kv)
		if err != nil {
			// 写入类似这样 {"Key":"21","Value":""}
			log.Fatal("重新编码 kv 为json对象失败---", kv)
		}
	}

	// 5. 写入操作完成之后， 关闭所有的文件
	for _, file := range intermediateFiles {
		file.Close()
	}
	//*/

}

func ihash(s string) int {
	h := fnv.New32a()
	h.Write([]byte(s))
	// 0x7fffffff 是 long int 的最大值
	return int(h.Sum32() & 0x7fffffff)
}
